# Makefile for hisi kirin ISP driver

isp-y := hisi_isp_core.o \
		hisi_isp_common.o \
		hisi_isp_csi.o \
		hisi_isp_sr.o \
		hisi_isp_cvdr.o \
		hisi_isp_isr.o \
		i2c.o \
		ov5645.o

obj-$(CONFIG_HISI_KIRIN_ISP) += isp.o
